/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ONITAMA;

import java.awt.GridLayout;
import javax.swing.JButton;

/**
 *
 * @author redou
 */
public class Jeu_Principale extends javax.swing.JFrame {
    GrilleDeJeuO grille;
    /**
     * Creates new form Jeu_Principale
     */
    public void initialiserPartie() {
        grille.initialiserGrille();
    }
    public Jeu_Principale() {
        initComponents();
        this.grille = new GrilleDeJeuO(5,5);
        PanneauGrille.setLayout(new GridLayout(5, 5));
        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200,5*110, 5*110));
            this.pack();
            this.revalidate();
        for (int i=0; i < 5; i++) {
            for (int j=0; j < 5; j++ ) {
                CelluleGraph bouton_cellule = new CelluleGraph(grille.matriceCellules[i][j], 110,110);
                PanneauGrille.add(bouton_cellule); // ajout au Jpanel PanneauGrille
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauGrille = new javax.swing.JPanel();
        PanneauGrille5 = new javax.swing.JPanel();
        PanneauGrille9 = new javax.swing.JPanel();
        PanneauGrille10 = new javax.swing.JPanel();
        PanneauGrille11 = new javax.swing.JPanel();
        PanneauGrille12 = new javax.swing.JPanel();
        PanneauGrille1 = new javax.swing.JPanel();
        PanneauGrille2 = new javax.swing.JPanel();
        PanneauGrille3 = new javax.swing.JPanel();
        PanneauGrille4 = new javax.swing.JPanel();
        PanneauGrille13 = new javax.swing.JPanel();
        PanneauGrille14 = new javax.swing.JPanel();
        PanneauGrille15 = new javax.swing.JPanel();
        PanneauGrille16 = new javax.swing.JPanel();
        PanneauGrille17 = new javax.swing.JPanel();
        PanneauGrille18 = new javax.swing.JPanel();
        PanneauGrille19 = new javax.swing.JPanel();
        PanneauGrille20 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(-10, 0));
        setMaximumSize(new java.awt.Dimension(2400, 890));
        setMinimumSize(new java.awt.Dimension(2400, 890));
        setPreferredSize(new java.awt.Dimension(2400, 890));
        setSize(new java.awt.Dimension(2400, 890));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PanneauGrille.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 600, 600));

        PanneauGrille5.setBackground(new java.awt.Color(102, 102, 102));
        PanneauGrille5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        PanneauGrille5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(PanneauGrille5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 280, 130));

        PanneauGrille9.setBackground(new java.awt.Color(102, 102, 102));
        PanneauGrille9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        PanneauGrille9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille10.setBackground(new java.awt.Color(102, 102, 102));
        PanneauGrille10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PanneauGrille10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanneauGrille9.add(PanneauGrille10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 280, 110));

        PanneauGrille11.setBackground(new java.awt.Color(102, 102, 102));
        PanneauGrille11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PanneauGrille11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille12.setBackground(new java.awt.Color(102, 102, 102));
        PanneauGrille12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PanneauGrille12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanneauGrille11.add(PanneauGrille12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 280, 110));

        PanneauGrille9.add(PanneauGrille11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 280, 130));

        getContentPane().add(PanneauGrille9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 280, 130));

        PanneauGrille1.setBackground(new java.awt.Color(102, 102, 102));
        PanneauGrille1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        PanneauGrille1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille2.setBackground(new java.awt.Color(102, 102, 102));
        PanneauGrille2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PanneauGrille2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanneauGrille1.add(PanneauGrille2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 280, 110));

        PanneauGrille3.setBackground(new java.awt.Color(102, 102, 102));
        PanneauGrille3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PanneauGrille3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille4.setBackground(new java.awt.Color(102, 102, 102));
        PanneauGrille4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PanneauGrille4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanneauGrille3.add(PanneauGrille4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 280, 110));

        PanneauGrille1.add(PanneauGrille3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 280, 130));

        getContentPane().add(PanneauGrille1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 280, 130));

        PanneauGrille13.setBackground(new java.awt.Color(102, 102, 102));
        PanneauGrille13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        PanneauGrille13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille14.setBackground(new java.awt.Color(102, 102, 102));
        PanneauGrille14.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PanneauGrille14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanneauGrille13.add(PanneauGrille14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 280, 110));

        PanneauGrille15.setBackground(new java.awt.Color(102, 102, 102));
        PanneauGrille15.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PanneauGrille15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille16.setBackground(new java.awt.Color(102, 102, 102));
        PanneauGrille16.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PanneauGrille16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanneauGrille15.add(PanneauGrille16, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 280, 110));

        PanneauGrille13.add(PanneauGrille15, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 280, 130));

        getContentPane().add(PanneauGrille13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 490, 280, 130));

        PanneauGrille17.setBackground(new java.awt.Color(102, 102, 102));
        PanneauGrille17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        PanneauGrille17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille18.setBackground(new java.awt.Color(102, 102, 102));
        PanneauGrille18.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PanneauGrille18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanneauGrille17.add(PanneauGrille18, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 280, 110));

        PanneauGrille19.setBackground(new java.awt.Color(102, 102, 102));
        PanneauGrille19.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PanneauGrille19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille20.setBackground(new java.awt.Color(102, 102, 102));
        PanneauGrille20.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PanneauGrille20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanneauGrille19.add(PanneauGrille20, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 280, 110));

        PanneauGrille17.add(PanneauGrille19, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 280, 130));

        getContentPane().add(PanneauGrille17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 280, 280, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jeu_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jeu_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jeu_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jeu_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jeu_Principale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauGrille;
    private javax.swing.JPanel PanneauGrille1;
    private javax.swing.JPanel PanneauGrille10;
    private javax.swing.JPanel PanneauGrille11;
    private javax.swing.JPanel PanneauGrille12;
    private javax.swing.JPanel PanneauGrille13;
    private javax.swing.JPanel PanneauGrille14;
    private javax.swing.JPanel PanneauGrille15;
    private javax.swing.JPanel PanneauGrille16;
    private javax.swing.JPanel PanneauGrille17;
    private javax.swing.JPanel PanneauGrille18;
    private javax.swing.JPanel PanneauGrille19;
    private javax.swing.JPanel PanneauGrille2;
    private javax.swing.JPanel PanneauGrille20;
    private javax.swing.JPanel PanneauGrille3;
    private javax.swing.JPanel PanneauGrille4;
    private javax.swing.JPanel PanneauGrille5;
    private javax.swing.JPanel PanneauGrille9;
    // End of variables declaration//GEN-END:variables
}
