/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JEU;

import java.awt.GridLayout;


/**
 *
 * @author redou
 */
public class Jeu_Principale extends javax.swing.JFrame {
    Plateau plateau;
    /**
     * Creates new form Jeu_Principale
     */

    public Jeu_Principale() {
        initComponents();
        this.plateau = new Plateau();
        PanneauGrille.setLayout(new GridLayout(5, 5));
        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200,5*110, 5*110));
            this.pack();
            this.revalidate();
        for (int i=0; i < 5; i++) {
            for (int j=0; j < 5; j++ ) {
                Case bouton_cellule = new Case(plateau.grille.grille[i][j], 110,110);
                PanneauGrille.add(bouton_cellule); // ajout au Jpanel PanneauGrille
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauGrille = new javax.swing.JPanel();
        Carte5 = new javax.swing.JButton();
        Carte4 = new javax.swing.JButton();
        Carte2 = new javax.swing.JButton();
        Carte1 = new javax.swing.JButton();
        Carte3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(-10, 0));
        setMaximumSize(new java.awt.Dimension(2400, 890));
        setMinimumSize(new java.awt.Dimension(2400, 890));
        setPreferredSize(new java.awt.Dimension(2400, 890));
        setSize(new java.awt.Dimension(900, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PanneauGrille.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 600, 600));

        Carte5.setText("jButton1");
        Carte5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carte5ActionPerformed(evt);
            }
        });
        getContentPane().add(Carte5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 420, 270, 100));

        Carte4.setText("jButton1");
        getContentPane().add(Carte4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 290, 270, 100));

        Carte2.setText("jButton1");
        Carte2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carte2ActionPerformed(evt);
            }
        });
        getContentPane().add(Carte2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 270, 100));

        Carte1.setText("jButton1");
        Carte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Carte1ActionPerformed(evt);
            }
        });
        getContentPane().add(Carte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 270, 100));

        Carte3.setText("jButton1");
        getContentPane().add(Carte3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 270, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Carte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carte1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Carte1ActionPerformed

    private void Carte2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carte2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Carte2ActionPerformed

    private void Carte5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Carte5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Carte5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jeu_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jeu_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jeu_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jeu_Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jeu_Principale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Carte1;
    private javax.swing.JButton Carte2;
    private javax.swing.JButton Carte3;
    private javax.swing.JButton Carte4;
    private javax.swing.JButton Carte5;
    private javax.swing.JPanel PanneauGrille;
    // End of variables declaration//GEN-END:variables
}
