/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package threes;

import java.awt.GridLayout;
import javax.swing.JButton;

/**
 *
 * @author anaza
 */
public class GrilleDeJeuThrees extends javax.swing.JFrame {
    Grille grille; 
    int nbL;
    int nbC;

    /**
     * Creates new form GrilleDeJeuThrees
     */
    public GrilleDeJeuThrees() {
        initComponents();
        nbL=4;
        nbC=4;
        grille = new Grille(nbL,nbC);
        GrilleJeu.setLayout(new GridLayout(nbL, nbC));
        for (int i = 1; i <= nbL; i++) {
            for (int j = 1; j <= nbC; j++) {
                //CelluleGraph cellule = new CelluleGraph( grille.matriceCellules[i][j], 36,36);
                JButton cellule =new JButton();
                GrilleJeu.add(cellule); 
            }
        }
        
        this.pack();
        this.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrilleJeu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GrilleJeu.setBackground(new java.awt.Color(51, 255, 204));

        javax.swing.GroupLayout GrilleJeuLayout = new javax.swing.GroupLayout(GrilleJeu);
        GrilleJeu.setLayout(GrilleJeuLayout);
        GrilleJeuLayout.setHorizontalGroup(
            GrilleJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        GrilleJeuLayout.setVerticalGroup(
            GrilleJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(GrilleJeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 400, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrilleDeJeuThrees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrilleDeJeuThrees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrilleDeJeuThrees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrilleDeJeuThrees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GrilleDeJeuThrees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GrilleJeu;
    // End of variables declaration//GEN-END:variables
}
